import type { NextPage } from 'next';
import Head from 'next/head';
import Image from 'next/image';
import Header from '../components/header';
import React, { useState } from 'react';
import Selector from '../components/selector';
import { CoinType } from '../components/coin';
import Results, { IGameResults } from '../components/results';
import RulesModal from '../components/rules-modal';

const checkUserWon = (results: IGameResults) => {
  const { userChoice, botChoice } = results;
  // Implement rock paper scissors lizard spock logic
  if (userChoice === botChoice) {
    return null;
  }
  if (userChoice === CoinType.ROCK) {
    return botChoice === CoinType.SCISSORS || botChoice === CoinType.LIZARD;
  }
  if (userChoice === CoinType.PAPER) {
    return botChoice === CoinType.ROCK || botChoice === CoinType.SPOCK;
  }
  if (userChoice === CoinType.SCISSORS) {
    return botChoice === CoinType.PAPER || botChoice === CoinType.LIZARD;
  }
  if (userChoice === CoinType.LIZARD) {
    return botChoice === CoinType.SPOCK || botChoice === CoinType.PAPER;
  }
  if (userChoice === CoinType.SPOCK) {
    return botChoice === CoinType.LIZARD || botChoice === CoinType.ROCK;
  }
  return null;
};

const Home: NextPage = () => {
  const [results, setResults] = useState<IGameResults | null>(null);
  const [score, setScore] = useState(0);
  const [userWon, setUserWon] = useState<boolean | null>(null);

  const selectCoin = (userChoice: CoinType, botChoice: CoinType) => {
    const newResults = { userChoice, botChoice };
    const newUserWon = checkUserWon(newResults);
    console.log(newUserWon);
    const update = newUserWon == null ? 0 : newUserWon ? 1 : -1;
    setUserWon(newUserWon);
    setResults(newResults);
    setScore(score + update);
  };

  const clearResults = () => {
    setResults(null);
  };

  return (
    <div className="container">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="background flex flex-col items-center w-screen px-8 h-screen pt-12">
        <Header score={score} />
        {results ? (
          <Results
            results={results}
            userWon={userWon}
            clearResults={clearResults}
          />
        ) : (
          <Selector onSelect={selectCoin} />
        )}
      </main>
    </div>
  );
};

export default Home;
