import type { NextPage } from 'next';
import Head from 'next/head';
import Image from 'next/image';
import Header from '../components/header';
import Coin, { CoinColor, CoinType } from '../components/coin';

const Home: NextPage = () => {
  return (
    <div className="container">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="background flex flex-col items-center w-screen h-screen p-10">
        <Header />

        <div className="relative h-full z-10 w-2/3 px-48 mt-12">
          <Image
            src="/images/bg-pentagon.svg"
            layout="responsive"
            alt="logo"
            height={400}
            width={400}
          />
          <div className="absolute top-0 left-1/2 -translate-x-1/2">
            <Coin color={CoinColor.YELLOW} type={CoinType.SCISSORS} />
          </div>
          <div className="absolute top-1/4 left-1/4 -translate-x-1/2">
            <Coin color={CoinColor.GREEN} type={CoinType.SPOCK} />
          </div>
          <div className="absolute top-1/4 left-3/4 -translate-x-1/2">
            <Coin color={CoinColor.BLUE} type={CoinType.PAPER} />
          </div>
          <div className="absolute top-2/3 left-1/3 -translate-x-1/2">
            <Coin color={CoinColor.PURPLE} type={CoinType.LIZARD} />
          </div>
          <div className="absolute top-2/3 left-2/3 -translate-x-1/2">
            <Coin color={CoinColor.RED} type={CoinType.ROCK} />
          </div>
        </div>
      </main>
    </div>
  );
};

export default Home;
